spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true